name: cd HelloWorldFunction

on:
  push:
    branches:
      - config/12-gitAction-cd-setting
    paths:
      - 'HelloWorldFunction/**'  # ✅

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Build
        run: |
          cd HelloWorldFunction  # ✅
          chmod +x gradlew
          ./gradlew clean build

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

            # SAM build (HelloWorldFunction만)
      - name: SAM Build
        run: sam build HelloWorldFunction

        # SAM deploy (전체 스택 업데이트, 하지만 실제로는 변경된 함수만)
      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name Project02-SpeakTracker \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --region ap-northeast-2